// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRMAgreement.Data_Base;

#nullable disable

namespace SRMAgreement.Migrations.DataBaseArchiveMigrations
{
    [DbContext(typeof(DataBaseArchive))]
    [Migration("20240719081506_Update-Archive-1")]
    partial class UpdateArchive1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SRMAgreement.Class.Archive_3D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AktDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogovirOrendu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prumitka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StrokDii")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Archive_3D");
                });

            modelBuilder.Entity("SRMAgreement.Class.Archive_4D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AktDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogovirSuborendu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prumitka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StrokDii")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Archive_4D");
                });

            modelBuilder.Entity("SRMAgreement.Class.Archive_5D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumDog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OhronnaComp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResPerson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StrokDii")
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Archive_5D");
                });

            modelBuilder.Entity("SRMAgreement.Class.Archive_6D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanckAccount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameTov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnifiedStateRegister")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Archive_6D");
                });
#pragma warning restore 612, 618
        }
    }
}
