// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRMAgreement.Data_Base;

#nullable disable

namespace SRMAgreement.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20241002182054_Update-D2-Add-two")]
    partial class UpdateD2Addtwo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SRMAgreement.Class.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("status");
                });

            modelBuilder.Entity("SRMAgreement.Class.SubleaseDop", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Num")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("rnokpp")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubleaseDop");
                });

            modelBuilder.Entity("SRMAgreement.Class._1D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanckAccount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResPerson")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Tov")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("edryofop_Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rnokpp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("D1");
                });

            modelBuilder.Entity("SRMAgreement.Class._2D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCloseDepartment")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PIBS")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubleaseDopId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("area")
                        .HasColumnType("REAL");

                    b.Property<bool?>("isAlert")
                        .HasColumnType("INTEGER");

                    b.Property<string>("rent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubleaseDopId")
                        .IsUnique();

                    b.ToTable("D2");
                });

            modelBuilder.Entity("SRMAgreement.Class._3D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AktDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogovirOrendu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prumitka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StrokDii")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("D3");
                });

            modelBuilder.Entity("SRMAgreement.Class._4D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AktDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogovirSuborendu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndAktDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Suma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("D4");
                });

            modelBuilder.Entity("SRMAgreement.Class._4DBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DogovirSuborendu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndAktDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StrokDii")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("D4Bookk");
                });

            modelBuilder.Entity("SRMAgreement.Class._5D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumDog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OhronnaComp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathToFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResPerson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StrokDii")
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("D5");
                });

            modelBuilder.Entity("SRMAgreement.Class._6D", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BanckAccount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameTov")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnifiedStateRegister")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("D6");
                });

            modelBuilder.Entity("SRMAgreement.Class._2D", b =>
                {
                    b.HasOne("SRMAgreement.Class.SubleaseDop", "SubleaseDop")
                        .WithOne("_2D")
                        .HasForeignKey("SRMAgreement.Class._2D", "SubleaseDopId");

                    b.Navigation("SubleaseDop");
                });

            modelBuilder.Entity("SRMAgreement.Class.SubleaseDop", b =>
                {
                    b.Navigation("_2D");
                });
#pragma warning restore 612, 618
        }
    }
}
